const products = [
  {
    createdDate: "20 June at 00:00:00 UTC+1",
    productAdminUserUID: "AWDjaaoWAIRiomfNMUITNkj2",
    productCategory: "necklace",
    productName: "Necklace One",
    productPrice: "120.00",
    productThumbnail: "https://pbs.twimg.com/media/FE1P6dIVgAUbhpG?format=jpg&name=medium",
    productFeatured: true,
  },
  {
    createdDate: "20 June at 00:00:00 UTC+1",
    productAdminUserUID: "AWDjaaoWAIRiomfNMUITNkj2",
    productCategory: "necklace",
    productName: "Necklace Two",
    productPrice: "100.00",
    productThumbnail: "https://pbs.twimg.com/media/FE1PngoVcAACm4O?format=jpg&name=medium",
    productFeatured: false,
  },
  {
    createdDate: "20 June at 00:00:00 UTC+1",
    productAdminUserUID: "AWDjaaoWAIRiomfNMUITNkj2",
    productCategory: "necklace",
    productName: "Necklace Three",
    productPrice: "110.00",
    productThumbnail: "https://pbs.twimg.com/media/FEzKKZKVgAEydhU?format=jpg&name=medium",
    productFeatured: true,
  },
  {
    createdDate: "20 June at 00:00:00 UTC+1",
    productAdminUserUID: "AWDjaaoWAIRiomfNMUITNkj2",
    productCategory: "necklace",
    productName: "Necklace Four",
    productPrice: "90.00",
    productThumbnail: "https://pbs.twimg.com/media/FEzJcp-VQAMgIh2?format=jpg&name=medium",
    productFeatured: false,
  },
  {
    createdDate: "20 June at 00:00:00 UTC+1",
    productAdminUserUID: "AWDjaaoWAIRiomfNMUITNkj2",
    productCategory: "necklace",
    productName: "Necklace Five",
    productPrice: "120.00",
    productThumbnail: "https://pbs.twimg.com/media/FEzJagmVcAMotrx?format=jpg&name=medium",
    productFeatured: true,
  },
  {
    createdDate: "20 June at 00:00:00 UTC+1",
    productAdminUserUID: "AWDjaaoWAIRiomfNMUITNkj2",
    productCategory: "necklace",
    productName: "Necklace Six",
    productPrice: "150.00",
    productThumbnail: "https://pbs.twimg.com/media/FEzJZaSUUAACj0m?format=jpg&name=medium",
    productFeatured: true,
  },
  {
    createdDate: "20 June at 00:00:00 UTC+1",
    productAdminUserUID: "AWDjaaoWAIRiomfNMUITNkj2",
    productCategory: "necklace",
    productName: "Necklace Seven",
    productPrice: "90.00",
    productThumbnail: "https://pbs.twimg.com/media/FEzJXcdVQAcotXw?format=jpg&name=medium",
    productFeatured: false,
  },
  {
    createdDate: "20 June at 00:00:00 UTC+1",
    productAdminUserUID: "AWDjaaoWAIRiomfNMUITNkj2",
    productCategory: "necklace",
    productName: "Necklace Eight",
    productPrice: "120.00",
    productThumbnail: "https://pbs.twimg.com/media/FEzJVF9VkAAIWaK?format=jpg&name=medium",
    productFeatured: true,
  },
  {
    createdDate: "20 June at 00:00:00 UTC+1",
    productAdminUserUID: "AWDjaaoWAIRiomfNMUITNkj2",
    productCategory: "necklace",
    productName: "Necklace Nine",
    productPrice: "150.00",
    productThumbnail: "https://pbs.twimg.com/media/FEzJSkyVIAcTBeq?format=jpg&name=medium",
    productFeatured: true,
  },
  {
    createdDate: "20 June at 00:00:00 UTC+1",
    productAdminUserUID: "AWDjaaoWAIRiomfNMUITNkj2",
    productCategory: "necklace",
    productName: "Necklace Ten",
    productPrice: "110.00",
    productThumbnail: "https://pbs.twimg.com/media/FEzJPVeUUAUASBi?format=jpg&name=medium",
    productFeatured: true,
  },
];

export default products;
